services:
  super-s3:
    build: .
    image: super-s3:latest
    container_name: super-s3
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config/config.yaml
    environment:
      - CONFIG_PATH=/config/config.yaml
    restart: unless-stopped
